# Generated by Django 5.0.3 on 2026-01-15 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='职位标题')),
                ('requirement', models.TextField(verbose_name='职位要求')),
                ('duty', models.TextField(verbose_name='职位职责')),
                ('salary', models.CharField(help_text='薪资范围或金额', max_length=100, verbose_name='薪资')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company_user', models.ForeignKey(help_text='发布职位的公司用户', on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='users.user', verbose_name='公司用户')),
            ],
            options={
                'verbose_name': '职位',
                'verbose_name_plural': '职位',
                'db_table': 'jobs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['company_user'], name='jobs_company_35fdfd_idx'), models.Index(fields=['-created_at'], name='jobs_created_91fc39_idx')],
            },
        ),
    ]
